import type { Product, Order } from './types'

export const CATEGORIES = [
  { id: 'all', label: 'Hammasi', emoji: '🍽️' },
  { id: 'osh', label: 'Osh / Palov', emoji: '🥘' },
  { id: 'shashlik', label: 'Shashliklar', emoji: '🍢' },
  { id: 'somsa', label: 'Somsalar', emoji: '🥟' },
  { id: 'milliy', label: 'Milliy taomlar', emoji: '🍲' },
  { id: 'lagmon', label: 'Lagʻmonlar', emoji: '🍜' },
  { id: 'fastfood', label: 'Fast Food', emoji: '🍔' },
  { id: 'ichimliklar', label: 'Ichimliklar', emoji: '🥤' },
  { id: 'shirinliklar', label: 'Shirinliklar', emoji: '🍰' },
]

export const PRODUCTS: Product[] = [
  // --- OSH / PALOV ---
  {
    id: 'osh-1',
    name: "Toshkent To'y Oshi",
    description: "Dumba yog'i, sara mol go'shti, sariq sabzi, no'xat, mayiz va zira bilan damlangan mashhur to'y oshi",
    price: 42000,
    oldPrice: 48000,
    discount: 12,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Lazer guruch', "Mol go'shti", 'Dumba', 'Sariq sabzi', "No'xat", 'Mayiz', 'Zira'],
    extras: [
      { name: "Qazi (2 bo'lak)", price: 12000 },
      { name: 'Bedana tuxumi (2 dona)', price: 4000 },
      { name: 'Achchiq-chuchuk salati', price: 6000 },
    ],
    inStock: true,
  },
  {
    id: 'osh-2',
    name: 'Choyxona Palov',
    description: "Devzira guruch va to'yimli qo'y go'shtidan an'anaviy choyxona uslubida tayyorlangan sersuv osh",
    price: 46000,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Devzira guruch', "Qo'y go'shti", 'Qizil sabzi', 'Piyoz', 'Sarimsoq', 'Zira'],
    extras: [
      { name: "Qo'shimcha go'sht (100g)", price: 18000 },
      { name: 'Achchiq qalampir', price: 2000 },
    ],
    inStock: true,
  },

  // --- SHASHLIKLAR ---
  {
    id: 'shash-1',
    name: "Qo'y Go'shti Shashlik",
    description: "Mangal cho'g'ida pishirilgan mayin va sersuv qo'y go'shti dumba bilan",
    price: 24000,
    oldPrice: 28000,
    discount: 14,
    category: 'shashlik',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Qo'y go'shti", 'Dumba', 'Piyoz', "Ziravorlar to'plami"],
    extras: [
      { name: "Marinadlangan piyoz va ko'katlar", price: 2000 },
      { name: 'Maxsus tomatli sous', price: 3000 },
      { name: 'Tandir non', price: 5000 },
    ],
    inStock: true,
  },
  {
    id: 'shash-2',
    name: 'Qiyma Shashlik',
    description: "Maxsus retsept bo'yicha maydalangan mol go'shti va dumbadan tayyorlangan og'izda eriydigan shashlik",
    price: 19000,
    category: 'shashlik',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Mol go'shti qiymasi", 'Dumba', 'Piyoz', 'Zira', 'Murch'],
    extras: [
      { name: "Marinadlangan piyoz", price: 1500 },
      { name: 'Achchiq sous', price: 2500 },
    ],
    inStock: true,
  },
  {
    id: 'shash-3',
    name: 'Jigar Shashlik (Dumba bilan)',
    description: "Yangi mol jigari mayin dumba bo'laklari bilan o'ralgan holatda pishirilgan",
    price: 18000,
    category: 'shashlik',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Mol jigari', 'Dumba', 'Ziravorlar'],
    extras: [{ name: 'Tomat sousi', price: 3000 }],
    inStock: true,
  },

  // --- SOMSALAR ---
  {
    id: 'somsa-1',
    name: "Tandir Go'shtli Somsa",
    description: "Qatlama xamir, mayda to'g'ralgan mol go'shti, dumba va piyoz bilan tandirda qizartirib pishirilgan",
    price: 12000,
    category: 'somsa',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Qatlama xamir', "Mol go'shti", 'Dumba', 'Piyoz', 'Sedana'],
    extras: [{ name: 'Achchiq pomidor sousi', price: 2000 }],
    inStock: true,
  },
  {
    id: 'somsa-2',
    name: 'Qovoqli Somsa',
    description: "Xushbo'y shirin qovoq va nozik ziravorlar bilan to'ldirilgan parhez tandir somsa",
    price: 8000,
    category: 'somsa',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Qatlama xamir', 'Shirin qovoq', 'Piyoz', 'Sedana'],
    extras: [],
    inStock: true,
  },

  // --- MILLIY TAOMLAR ---
  {
    id: 'milliy-1',
    name: 'Qozon Kabob',
    description: "Qozonda qizarguncha qovurilgan yosh buzoqcha qovurg'alari va tillarang qovurilgan kartoshka",
    price: 68000,
    oldPrice: 75000,
    discount: 10,
    category: 'milliy',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Mol qovurg'asi", 'Kichik kartoshkalar', 'Piyoz', "Ko'katlar", 'Zira'],
    extras: [
      { name: 'Tandir issiq non', price: 5000 },
      { name: 'Suzma koʻkatlar bilan', price: 5000 },
    ],
    inStock: true,
  },
  {
    id: 'milliy-2',
    name: 'Goʻshtli Manti (4 dona)',
    description: "Yupqa cho'ziluvchan xamir, mayin to'g'ralgan go'sht va dumbadan bug'da pishirilgan manti",
    price: 36000,
    category: 'milliy',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Yupqa xamir', "Mol go'shti", 'Dumba yogʻi', 'Piyoz', 'Qora murch'],
    extras: [
      { name: 'Smetana / Suzma', price: 4000 },
      { name: 'Qalampirli sous', price: 2000 },
    ],
    inStock: true,
  },
  {
    id: 'milliy-3',
    name: "Qo'y Go'shtli Sho'rva",
    description: "Yangi qo'y go'shti, sabzi, kartoshka va no'xat solingan to'yimli an'anaviy sho'rva",
    price: 34000,
    category: 'milliy',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Qo'y go'shti", 'Kartoshka', 'Sabzi', "No'xat", "Ko'katlar"],
    extras: [{ name: 'Tandir non', price: 5000 }],
    inStock: true,
  },
  {
    id: 'milliy-4',
    name: 'Issiq Tandir Non',
    description: "Sedana va kunjut sepilgan, tandirdan yangi uzilgan xushbo'y non",
    price: 5000,
    category: 'milliy',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Oliy navli un', 'Sedana', 'Kunjut'],
    extras: [],
    inStock: true,
  },

  // --- LAG'MONLAR ---
  {
    id: 'lagmon-1',
    name: "Uyg'ur Cho'zma Lag'mon",
    description: "Qo'lda cho'zilgan xamir, sersuv mol go'shti, sabzavotlar va xushbo'y gravyuradan iborat lag'mon",
    price: 38000,
    category: 'lagmon',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Cho'zma xamir", "Mol go'shti", "Bulg'or qalampiri", 'Piyoz', 'Pomidor', 'Seldr'],
    extras: [
      { name: 'Laza (achchiq sous)', price: 2000 },
      { name: "Qo'shimcha go'sht", price: 10000 },
    ],
    inStock: true,
  },
  {
    id: 'lagmon-2',
    name: "Qovurma Lag'mon",
    description: "Wok tovada go'sht, tuxum va sabzavotlar bilan baland olovda qovurilgan xushta'm cho'zma lag'mon",
    price: 40000,
    oldPrice: 45000,
    discount: 11,
    category: 'lagmon',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Cho'zma xamir", "Mol go'shti", 'Tuxum', "Bulg'or qalampiri", 'Maxsus sous'],
    extras: [{ name: 'Laza sousi', price: 2000 }],
    inStock: true,
  },

  // --- FAST FOOD ---
  {
    id: 'ff-1',
    name: 'Pepperoni Pizza',
    description: "Yangi pomidor sousi, mozzarella pishloq va achchiqroq pepperoni bilan tayyorlangan pitsa",
    price: 52000,
    oldPrice: 62000,
    discount: 16,
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Mozzarella', 'Pomidor sousi', 'Pepperoni', 'Zaytun', 'Oregano'],
    extras: [
      { name: "Qo'shimcha pishloq", price: 6000 },
      { name: 'Coca-Cola 0.5L', price: 8000 },
    ],
    inStock: true,
  },
  {
    id: 'ff-2',
    name: 'Classic Burger',
    description: "100% sara mol go'shti kotleti, yangi aysberg salati, pomidor va maxsus burger sousi",
    price: 38000,
    oldPrice: 44000,
    discount: 14,
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Mol go'shti kotleti", 'Salat bargi', 'Pomidor', 'Cheddar pishloq', 'Sous'],
    extras: [
      { name: "Qo'shimcha kotlet", price: 14000 },
      { name: 'Kartoshka fri', price: 9000 },
    ],
    inStock: true,
  },
  {
    id: 'ff-3',
    name: 'Tovuqli Lavash (Katta)',
    description: "Yupqa lavash xamiri, marinadlangan tovuq go'shti, sabzavotlar va mayin oq sous",
    price: 32000,
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Tovuq go'shti", 'Salat', 'Pomidor', 'Bodring', 'Maxsus sous'],
    extras: [
      { name: 'Pishloq qoʻshish', price: 4000 },
      { name: 'Achchiq sous', price: 2000 },
    ],
    inStock: true,
  },

  // --- ICHIMLIKLAR ---
  {
    id: 'ichim-1',
    name: 'Coca-Cola 0.5L',
    description: 'Muzdek tetiklashtiruvchi klassik gazli ichimlik',
    price: 8000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=300&fit=crop&auto=format',
    ingredients: [],
    extras: [],
    inStock: true,
  },
  {
    id: 'ichim-2',
    name: 'Koʻk Choy (Limon bilan)',
    description: "Choynakda damlangan yangi ko'k choy va tabiiy limon bo'laklari",
    price: 6000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&h=300&fit=crop&auto=format',
    ingredients: ["Oliy navli ko'k choy", 'Limon', 'Navot'],
    extras: [],
    inStock: true,
  },
  {
    id: 'ichim-3',
    name: 'Gazsiz Toza Suv 0.5L',
    description: 'Tabiiy togʻ manbalari suvi',
    price: 4000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=400&h=300&fit=crop&auto=format',
    ingredients: [],
    extras: [],
    inStock: true,
  },

  // --- SHIRINLIKLAR ---
  {
    id: 'shirin-1',
    name: 'Namangan Paxlavasi',
    description: "Ko'p qatlamli yupqa xamir, yong'oq va tabiiy asal bilan tayyorlangan sharqona paxlava",
    price: 24000,
    category: 'shirinliklar',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Qatlama xamir', "Yong'oq", 'Tabiiy asal', 'Sariyogʻ'],
    extras: [],
    inStock: true,
  },
  {
    id: 'shirin-2',
    name: 'Shokoladli Tort',
    description: 'Nozik shokolad kremi bilan qoplangan yumshoq biskvitli tort',
    price: 22000,
    oldPrice: 28000,
    discount: 21,
    category: 'shirinliklar',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop&auto=format',
    ingredients: ['Shokolad', 'Krem', 'Biskvit', 'Kakao'],
    extras: [],
    inStock: true,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-101',
    number: 'A7K29',
    date: '15 yan, 14:32',
    items: [
      { product: PRODUCTS[0], quantity: 2, extras: ["Qazi (2 bo'lak)"], totalPrice: 108000 },
      { product: PRODUCTS[5], quantity: 3, extras: [], totalPrice: 36000 },
      { product: PRODUCTS[14], quantity: 2, extras: [], totalPrice: 16000 },
    ],
    subtotal: 160000,
    deliveryFee: 10000,
    discount: 5000,
    total: 165000,
    status: 'delivered',
    address: "Namangan sh., Boburshoh ko'chasi 24",
    courier: 'Aziz',
  },
  {
    id: 'ord-102',
    number: 'B3M71',
    date: '10 yan, 18:15',
    items: [
      { product: PRODUCTS[2], quantity: 3, extras: ["Marinadlangan piyoz va ko'katlar"], totalPrice: 78000 },
      { product: PRODUCTS[9], quantity: 2, extras: [], totalPrice: 10000 },
    ],
    subtotal: 88000,
    deliveryFee: 10000,
    discount: 5000,
    total: 93000,
    status: 'delivered',
    address: "Namangan sh., Chortoq shoh ko'chasi 11",
    courier: 'Sardor',
  },
  {
    id: 'ord-103',
    number: 'C9P14',
    date: 'Bugun, 12:05',
    items: [
      { product: PRODUCTS[0], quantity: 1, extras: [], totalPrice: 42000 },
      { product: PRODUCTS[7], quantity: 1, extras: ['Smetana / Suzma'], totalPrice: 40000 },
    ],
    subtotal: 82000,
    deliveryFee: 10000,
    discount: 5000,
    total: 87000,
    status: 'preparing',
    address: "Namangan sh., To'raqo'rg'on ko'chasi 45",
  },
]

export const formatPrice = (price: number) =>
  price.toLocaleString('uz-UZ').replace(/\s/g, ' ') + " so'm"
