import type { Product, Order } from './types'

export const CATEGORIES = [
  { id: 'all', label: 'Hammasi', emoji: '🍽️' },
  { id: 'kombo', label: 'Kombo & Setlar', emoji: '🍱' },
  { id: 'lavash', label: 'Lavashlar', emoji: '🌯' },
  { id: 'burger', label: 'Burger & Doner', emoji: '🍔' },
  { id: 'hotdog', label: 'Hot-doglar', emoji: '🌭' },
  { id: 'osh', label: 'Osh / Palov', emoji: '🥘' },
  { id: 'shashlik', label: 'Shashliklar', emoji: '🍢' },
  { id: 'somsa', label: 'Somsalar', emoji: '🥟' },
  { id: 'milliy', label: 'Milliy taomlar', emoji: '🍲' },
  { id: 'ichimliklar', label: 'Ichimliklar', emoji: '🥤' },
]

export const PRODUCTS: Product[] = [
  // --- KOMBO VA SETLAR ---
  {
    id: 'kombo-1',
    name: "Do'stlar Set",
    description: 'Oddiy lavash 5x, Coca-Cola 1.5L',
    price: 120000,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ['Oddiy lavash (5 dona)', 'Coca-Cola 1.5L'],
    extras: [{ name: "Qo'shimcha sous", price: 3000 }],
    inStock: true,
  },
  {
    id: 'kombo-2',
    name: 'Radnoylar Set',
    description: 'Oddiy lavash 3x, Coca-Cola 1.5L',
    price: 80000,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ['Oddiy lavash (3 dona)', 'Coca-Cola 1.5L'],
    extras: [{ name: "Qo'shimcha sous", price: 3000 }],
    inStock: true,
  },
  {
    id: 'kombo-3',
    name: 'Mix Set',
    description: 'Lavash oddiy 3x, Lavash tovuq 3x, Katta fri 1x, Coca-Cola 1.5L 1x',
    price: 160000,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ['Mol lavash 3x', 'Tovuq lavash 3x', 'Katta kartoshka fri 1x', 'Coca-Cola 1.5L 1x'],
    extras: [{ name: 'Pishloqli sous', price: 4000 }],
    inStock: true,
  },
  {
    id: 'kombo-k3-mol',
    name: "KOMBO 3 (Mol Go'shti)",
    description: 'Tandir lavash 3x, Katta fri 1x, Suv 3x',
    price: 140000,
    oldPrice: 152000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (mol) 3x', 'Katta fri 1x', 'Suv 3x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k3-bur',
    name: 'KOMBO 3 (Burger)',
    description: 'Burger 3x, Katta fri 1x, Suv 3x',
    price: 110000,
    oldPrice: 119000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    ingredients: ['Burger 3x', 'Katta fri 1x', 'Suv 3x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k3-tov',
    name: "KOMBO 3 (Tovuq Go'shti)",
    description: 'Tandir lavash 3x, Katta fri 1x, Suv 3x',
    price: 110000,
    oldPrice: 120000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (tovuq) 3x', 'Katta fri 1x', 'Suv 3x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k4-mol',
    name: "KOMBO 4 (Mol Go'shti)",
    description: 'Tandir lavash 4x, Katta fri 1x, Suv 4x',
    price: 180000,
    oldPrice: 196000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (mol) 4x', 'Katta fri 1x', 'Suv 4x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k4-bur',
    name: 'KOMBO 4 (Burger)',
    description: 'Burger 4x, Katta fri 1x, Suv 4x',
    price: 140000,
    oldPrice: 152000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    ingredients: ['Burger 4x', 'Katta fri 1x', 'Suv 4x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k4-tov',
    name: "KOMBO 4 (Tovuq Go'shti)",
    description: 'Tandir lavash 4x, Katta fri 1x, Suv 4x',
    price: 140000,
    oldPrice: 152000,
    discount: 8,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (tovuq) 4x', 'Katta fri 1x', 'Suv 4x'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k5-mol',
    name: "KOMBO 5 (Mol Go'shti)",
    description: 'Tandir lavash 5x, Katta fri 1x, Cola 1.5L',
    price: 215000,
    oldPrice: 231000,
    discount: 7,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (mol) 5x', 'Katta fri 1x', 'Coca-Cola 1.5L'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k5-bur',
    name: 'KOMBO 5 (Burger)',
    description: 'Burger 5x, Katta fri 1x, Cola 1.5L',
    price: 165000,
    oldPrice: 176000,
    discount: 6,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    ingredients: ['Burger 5x', 'Katta fri 1x', 'Coca-Cola 1.5L'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },
  {
    id: 'kombo-k5-tov',
    name: "KOMBO 5 (Tovuq Go'shti)",
    description: 'Tandir lavash 5x, Katta fri 1x, Cola 1.5L',
    price: 165000,
    oldPrice: 176000,
    discount: 6,
    category: 'kombo',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tandir lavash (tovuq) 5x', 'Katta fri 1x', 'Coca-Cola 1.5L'],
    extras: [{ name: "Pishloq qo'shish", price: 5000 }],
    inStock: true,
  },

  // --- LAVASH MOL GO'SHTI ---
  {
    id: 'lavash-mol-1',
    name: "Oddiy Lavash (Mol go'shti)",
    description: 'Yupqa xamirda sara mol go\'shti, pomidor, qarsildoq bodring va mayonez',
    price: 33000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti", 'Lavash xamiri', 'Pomidor', 'Bodring'],
    extras: [{ name: "Qo'shimcha pishloq", price: 4000 }, { name: 'Achchiq sous', price: 2000 }],
    inStock: true,
  },
  {
    id: 'lavash-mol-2',
    name: "Lavash Sir (Mol go'shti)",
    description: 'Mol go\'shti, golland pishlog\'i va xushbo\'y ziravorlar bilan to\'yimli lavash',
    price: 36000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti", 'Pishloq', 'Lavash xamiri', 'Sous'],
    extras: [{ name: 'Kartoshka fri qoʻshish', price: 5000 }],
    inStock: true,
  },
  {
    id: 'lavash-mol-3',
    name: "Tandir Lavash (Mol go'shti)",
    description: 'Tandir cho\'g\'ida qizartirib pishirilgan qarsildoq va xushta\'m tandir lavash',
    price: 39000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti", 'Tandir xamiri', 'Sous'],
    extras: [{ name: "Qo'shimcha pishloq", price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-mol-4',
    name: "Lavash Fri (Mol go'shti)",
    description: 'Mol go\'shti va qarsildoq kartoshka fri bilan to\'ldirilgan to\'yimli lavash',
    price: 42000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti", 'Kartoshka fri', 'Lavash xamiri', 'Sous'],
    extras: [{ name: "Qo'shimcha pishloq", price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-mol-5',
    name: "TT Lavash Big (Mol go'shti)",
    description: 'Katta hajm: ko\'p go\'sht, pishloq, qarsildoq fri va maxsus sirli sous',
    price: 45000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ["Ko'p mol go'shti", 'Pishloq', 'Fri', 'Maxsus sous'],
    extras: [{ name: "Qo'shimcha go'sht", price: 8000 }],
    inStock: true,
  },

  // --- LAVASH TOVUQ GO'SHTI ---
  {
    id: 'lavash-tov-1',
    name: 'Oddiy Lavash (Tovuq)',
    description: 'Yumshoq tovuq filesi, barra pomidor, bodring va yengil sous',
    price: 23000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ['Tovuq filesi', 'Lavash xamiri', 'Pomidor', 'Bodring'],
    extras: [{ name: "Pishloq qo'shish", price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-tov-2',
    name: 'Tandir Lavash (Tovuq)',
    description: 'Tandirda pishirilgan tovuqli lavash, qizarib pishgan qarsildoq xamir',
    price: 28000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tovuq filesi', 'Tandir xamiri', 'Sous'],
    extras: [{ name: "Pishloq qo'shish", price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-tov-3',
    name: 'Tandir Sir (Tovuq)',
    description: 'Tandirda erigan pishloq va mayin tovuq filesi uyg\'unligi',
    price: 30000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tovuq filesi', 'Pishloq', 'Tandir xamiri'],
    extras: [{ name: 'Fri qoʻshish', price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-tov-4',
    name: 'Tandir + Fri (Tovuq)',
    description: 'Tandirda pishgan tovuqli lavash ichida qarsildoq kartoshka fri',
    price: 33000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=400&h=300&fit=crop',
    ingredients: ['Tovuq filesi', 'Fri', 'Tandir xamiri', 'Sous'],
    extras: [{ name: "Pishloq qo'shish", price: 4000 }],
    inStock: true,
  },
  {
    id: 'lavash-tov-5',
    name: 'TT Lavash Fri + Sir (Tovuq)',
    description: 'Tovuq go\'shti, qo\'shaloq pishloq va fri bilan to\'yimli lavash',
    price: 38000,
    category: 'lavash',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    ingredients: ['Tovuq filesi', "Qo'shaloq pishloq", 'Fri', 'Sous'],
    extras: [{ name: "Qo'shimcha sous", price: 3000 }],
    inStock: true,
  },

  // --- BURGER & DONER ---
  {
    id: 'burger-1',
    name: 'Gamburger',
    description: 'Sara mol go\'shti kotleti, barra pomidor, bodring va mayin bulochka',
    price: 28000,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti kotleti", 'Bulochka', 'Pomidor', 'Bodring'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }, { name: 'Kartoshka fri', price: 9000 }],
    inStock: true,
  },
  {
    id: 'burger-2',
    name: 'Cheeseburger',
    description: 'Mol go\'shti kotleti, Chedder pishlog\'i, marinadlangan bodring va sous',
    price: 30000,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti kotleti", 'Chedder pishloq', 'Bulochka', 'Sous'],
    extras: [{ name: "Qo'shimcha kotlet", price: 12000 }],
    inStock: true,
  },
  {
    id: 'burger-3',
    name: 'TT Burger',
    description: 'Maxsus Tezkor Taom burgeri: qo\'shaloq kotlet, pishloq, tuxum va sirli sous',
    price: 38000,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&h=300&fit=crop',
    ingredients: ["Qo'shaloq kotlet", 'Pishloq', 'Tuxum', 'Maxsus sous'],
    extras: [{ name: 'Kartoshka fri', price: 9000 }],
    inStock: true,
  },
  {
    id: 'doner-1',
    name: 'Doner',
    description: 'Yupqa bulochkada mayin qovurilgan go\'sht, barra salat va sharqona sous',
    price: 26000,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
    ingredients: ["Go'sht", 'Bulochka', 'Salat', 'Sous'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'doner-2',
    name: 'Doner Sir (Pishloqli)',
    description: 'Erigan pishloq, mayin qovurilgan go\'sht va maxsus doner sousi',
    price: 28000,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
    ingredients: ["Go'sht", 'Erigan pishloq', 'Bulochka', 'Sous'],
    extras: [{ name: 'Achchiq sous', price: 2000 }],
    inStock: true,
  },

  // --- HOT-DOGLAR ---
  {
    id: 'hotdog-1',
    name: 'Kanadskiy Hot-dog',
    description: 'Sosiska, xantal, ketchup, mayonez va maxsus bodringli sous',
    price: 15000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=400&h=300&fit=crop',
    ingredients: ['Sosiska', 'Bulochka', 'Ketchup', 'Mayonez', 'Xantal'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'hotdog-2',
    name: 'Amerikano Hot-dog',
    description: 'Sersuv sosiska, qarsildoq piyoz, marinadlangan bodring va souslar',
    price: 18000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1627059397501-5231c6a287c8?w=400&h=300&fit=crop',
    ingredients: ['Sosiska', 'Bulochka', 'Qovurilgan piyoz', 'Marinadlangan bodring'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'hotdog-3',
    name: "Go'shtli Hot-dog",
    description: 'Sara qiyma go\'sht, sosiska va maxsus sous bilan boyitilgan hot-dog',
    price: 20000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1541214113241-21578d2d9b62?w=400&h=300&fit=crop',
    ingredients: ["Qiyma go'sht", 'Sosiska', 'Bulochka', 'Sous'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'hotdog-4',
    name: 'Longer',
    description: 'Uzun qarsildoq bulochka, maxsus go\'shtli to\'yimli hot-dog',
    price: 25000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1541214113241-21578d2d9b62?w=400&h=300&fit=crop',
    ingredients: ['Uzun bulochka', 'Sosiska', 'Pishloq', 'Sabzavotlar'],
    extras: [{ name: 'Sous', price: 2000 }],
    inStock: true,
  },
  {
    id: 'hotdog-5',
    name: 'Qazili Hot-dog',
    description: 'Haqiqiy ot go\'shti qazisi, xantal va maxsus ta\'mli souslar uyg\'unligi',
    price: 35000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=400&h=300&fit=crop',
    ingredients: ['Qazi', 'Bulochka', 'Xantal', 'Mayonez'],
    extras: [{ name: 'Qazi qoʻshimcha', price: 10000 }],
    inStock: true,
  },
  {
    id: 'hotdog-m1',
    name: 'Mangal Hot-dog 1',
    description: 'Mangal cho\'g\'ida dudlangan sosiska, maxsus mangal sousi va sabzavotlar',
    price: 28000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=400&h=300&fit=crop',
    ingredients: ['Dudlangan sosiska', 'Bulochka', 'Mangal sousi'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'hotdog-m2',
    name: 'Mangal Hot-dog 2',
    description: 'Mangal cho\'g\'ida pishgan qo\'sh sosiska va erigan pishloqli qatlam',
    price: 33000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1627059397501-5231c6a287c8?w=400&h=300&fit=crop',
    ingredients: ['Qo‘sh sosiska', 'Pishloq', 'Bulochka', 'Sous'],
    extras: [{ name: 'Fri qoʻshish', price: 4000 }],
    inStock: true,
  },
  {
    id: 'hotdog-m3',
    name: 'Mangal Hot-dog 3',
    description: 'Mangalda pishgan go\'sht, sosiska va qarsildoq kartoshka fri bilan',
    price: 38000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1627059397501-5231c6a287c8?w=400&h=300&fit=crop',
    ingredients: ["Go'sht", 'Sosiska', 'Fri', 'Sous'],
    extras: [{ name: "Pishloq qo'shish", price: 3000 }],
    inStock: true,
  },
  {
    id: 'hotdog-m4',
    name: 'Mangal Mix Hot-dog',
    description: 'Maxsus Mangal Mix: go\'sht, qazi, sosiska va erigan pishloq uyg\'unligi',
    price: 43000,
    category: 'hotdog',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=400&h=300&fit=crop',
    ingredients: ["Go'sht", 'Qazi', 'Sosiska', 'Pishloq', 'Fri'],
    extras: [{ name: 'Sous', price: 2000 }],
    inStock: true,
  },

  // --- OSH / PALOV ---
  {
    id: 'osh-1',
    name: "Toshkent To'y Oshi",
    description: 'Dumba yog\'i, sara mol go\'shti, sariq sabzi, no\'xat, mayiz va zira bilan damlangan mashhur to\'y oshi',
    price: 42000,
    oldPrice: 48000,
    discount: 12,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=400&h=300&fit=crop',
    ingredients: ['Lazer guruch', "Mol go'shti", 'Dumba', 'Sariq sabzi', "No'xat", 'Mayiz', 'Zira'],
    extras: [
      { name: "Qazi (2 bo'lak)", price: 12000 },
      { name: 'Bedana tuxumi (2 dona)', price: 4000 },
      { name: 'Achchiq-chuchuk salati', price: 6000 },
    ],
    inStock: true,
  },
  {
    id: 'osh-2',
    name: 'Choyxona Palov',
    description: 'Devzira guruch va to\'yimli qo\'y go\'shtidan an\'anaviy choyxona uslubida tayyorlangan sersuv osh',
    price: 46000,
    category: 'osh',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
    ingredients: ['Devzira guruch', "Qo'y go'shti", 'Qizil sabzi', 'Piyoz', 'Sarimsoq', 'Zira'],
    extras: [
      { name: "Qo'shimcha go'sht (100g)", price: 18000 },
      { name: 'Achchiq qalampir', price: 2000 },
    ],
    inStock: true,
  },

  // --- SHASHLIKLAR ---
  {
    id: 'shash-1',
    name: "Qo'y Go'shti Shashlik",
    description: 'Mangal cho\'g\'ida pishirilgan mayin va sersuv qo\'y go\'shti dumba bilan',
    price: 24000,
    oldPrice: 28000,
    discount: 14,
    category: 'shashlik',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
    ingredients: ["Qo'y go'shti", 'Dumba', 'Piyoz', "Ziravorlar to'plami"],
    extras: [
      { name: "Marinadlangan piyoz va ko'katlar", price: 2000 },
      { name: 'Maxsus tomatli sous', price: 3000 },
      { name: 'Tandir non', price: 5000 },
    ],
    inStock: true,
  },
  {
    id: 'shash-2',
    name: 'Qiyma Shashlik',
    description: 'Maxsus retsept bo\'yicha maydalangan mol go\'shti va dumbadan tayyorlangan og\'izda eriydigan shashlik',
    price: 19000,
    category: 'shashlik',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    ingredients: ["Mol go'shti qiymasi", 'Dumba', 'Piyoz', 'Zira', 'Murch'],
    extras: [
      { name: 'Marinadlangan piyoz', price: 1500 },
      { name: 'Achchiq sous', price: 2500 },
    ],
    inStock: true,
  },

  // --- SOMSALAR ---
  {
    id: 'somsa-1',
    name: "Tandir Go'shtli Somsa",
    description: 'Qatlama xamir, mayda to\'g\'ralgan mol go\'shti, dumba va piyoz bilan tandirda qizartirib pishirilgan',
    price: 12000,
    category: 'somsa',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
    ingredients: ['Qatlama xamir', "Mol go'shti", 'Dumba', 'Piyoz', 'Sedana'],
    extras: [{ name: 'Achchiq pomidor sousi', price: 2000 }],
    inStock: true,
  },

  // --- MILLIY TAOMLAR ---
  {
    id: 'milliy-1',
    name: 'Qozon Kabob',
    description: 'Qozonda qizarguncha qovurilgan yosh buzoqcha qovurg\'alari va tillarang qovurilgan kartoshka',
    price: 68000,
    oldPrice: 75000,
    discount: 10,
    category: 'milliy',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    ingredients: ["Mol qovurg'asi", 'Kichik kartoshkalar', 'Piyoz', "Ko'katlar", 'Zira'],
    extras: [
      { name: 'Tandir issiq non', price: 5000 },
      { name: 'Suzma koʻkatlar bilan', price: 5000 },
    ],
    inStock: true,
  },

  // --- ICHIMLIKLAR ---
  {
    id: 'ichim-1',
    name: 'Coca-Cola 1.5L',
    description: 'Katta oilaviy yoki do‘stlar davrasi uchun muzdek gazli ichimlik',
    price: 18000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=300&fit=crop',
    ingredients: [],
    extras: [],
    inStock: true,
  },
  {
    id: 'ichim-2',
    name: 'Coca-Cola 0.5L',
    description: 'Muzdek tetiklashtiruvchi klassik gazli ichimlik',
    price: 8000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=300&fit=crop',
    ingredients: [],
    extras: [],
    inStock: true,
  },
  {
    id: 'ichim-3',
    name: 'Koʻk Choy (Limon bilan)',
    description: 'Choynakda damlangan yangi ko\'k choy va tabiiy limon bo\'laklari',
    price: 6000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&h=300&fit=crop',
    ingredients: ["Oliy navli ko'k choy", 'Limon', 'Navot'],
    extras: [],
    inStock: true,
  },
  {
    id: 'ichim-4',
    name: 'Gazsiz Toza Suv 0.5L',
    description: 'Tabiiy togʻ manbalari suvi',
    price: 4000,
    category: 'ichimliklar',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=400&h=300&fit=crop',
    ingredients: [],
    extras: [],
    inStock: true,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-101',
    number: 'A7K29',
    date: 'Bugun, 14:32',
    items: [
      { product: PRODUCTS[0], quantity: 1, extras: [], totalPrice: 120000 },
      { product: PRODUCTS[12], quantity: 2, extras: [], totalPrice: 66000 },
    ],
    subtotal: 186000,
    deliveryFee: 10000,
    discount: 5000,
    total: 191000,
    status: 'delivered',
    address: "Namangan sh., Boburshoh ko'chasi 24",
    courier: 'Aziz Rahimov',
  },
  {
    id: 'ord-102',
    number: 'B3M71',
    date: 'Bugun, 13:15',
    items: [
      { product: PRODUCTS[4], quantity: 2, extras: ["Pishloq qo'shish"], totalPrice: 230000 },
    ],
    subtotal: 230000,
    deliveryFee: 10000,
    discount: 5000,
    total: 235000,
    status: 'delivered',
    address: "Namangan sh., Chortoq shoh ko'chasi 11",
    courier: 'Sardor Qodirov',
  },
  {
    id: 'ord-103',
    number: 'C9P14',
    date: 'Bugun, 12:05',
    items: [
      { product: PRODUCTS[22], quantity: 2, extras: [], totalPrice: 56000 },
      { product: PRODUCTS[27], quantity: 2, extras: [], totalPrice: 36000 },
    ],
    subtotal: 92000,
    deliveryFee: 10000,
    discount: 5000,
    total: 97000,
    status: 'preparing',
    address: "Namangan sh., To'raqo'rg'on ko'chasi 45",
  },
]

export const formatPrice = (price: number) =>
  price.toLocaleString('uz-UZ').replace(/\s/g, ' ') + " so'm"
